openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://172.17.0.2:8080
    description: Generated server url
x-wso2-basePath: /carrental/v1
x-wso2-production-endpoints:
  urls:
    - http://172.17.0.2:8080
paths:
  /rentCar:
    post:
      tags:
        - rental-controller
      operationId: bookCar
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RentalDetails"
        required: true
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/RentalDetails"
  /getCars:
    get:
      tags:
        - rental-controller
      operationId: getCars
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Car"
components:
  schemas:
    Car:
      type: object
      properties:
        name:
          type: string
        price:
          type: number
          format: double
        category:
          type: string
    RentalDetails:
      type: object
      properties:
        carDetail:
          $ref: "#/components/schemas/Car"
        fromDate:
          type: string
        toDate:
          type: string
        bookingStatus:
          type: string
        bookingName:
          type: string
        contactNumber:
          type: string
        contactEmail:
          type: string
